version: '3.8'

networks:
    webapp:
services:
    db:
        image: mysql
        container_name: mysql
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            MYSQL_ROOT_PASSWORD: dimas1950
            MYSQL_USER: dimas
            MYSQL_PASSWORD: dimas1950
            MYSQL_DATABASE: office
        networks:
            - webapp
    