version: '3.8'

networks:
    webapp:
services:
    db:
        image: mysql
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: dimas1950
            MYSQL_USER: dimas
            MYSQL_PASSWORD: dimas1950
            MYSQL_DATABASE: office
        networks:
            - webapp
    